baseurl = "https://inajob.netlify.com"
languageCode = "ja-JP"
title = "inajobのいろいろレビュー"

theme="theer"

[params]
ShareTo = ["Twitter", "Facebook", "Pocket", "Hatena"]
UseTwitterCard = true
Twitter = "ina_ani"
