baseurl = "https://inajob.github.io/iroiro-review"
languageCode = "ja-JP"
title = "inajobのいろいろレビュー"

theme="theer"

[params]
ShareTo = ["Twitter", "Facebook", "Pocket", "Hatena"]
UseTwitterCard = true
Twitter = "ina_ani"
Image = "/img/cover.png"

[markup.goldmark.renderer]
  unsafe = true

[related]

threshold = 80
includeNewer = false
toLower = false

[[related.indices]]
name  = "title"
weight = 50

[[related.indices]]
name  = "tags"
weight = 100

