name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          #submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.64.0'

      - name: Build
        run: yarn build

        #- name: Deploy
        #  uses: peaceiris/actions-gh-pages@v3
        #  with:
        #    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        #    publish_dir: ./public

