name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.64.0'

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup Modules
        run: yarn install

      - name: Build
        run: yarn build

      #- name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #    publish_dir: ./dist

      - name: Deploy to user page
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_REMOTE_KEY }}
          external_repository: inajob/iroiro-review
          publish_dir: ./dist

